/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'conanyuan' at '5/7/17 10:34 PM' with Gradle 2.14.1
 *
 * @author conanyuan, @date 5/7/17 10:34 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
